"""
Signal data model for trading signals from strategies.
"""

from datetime import datetime
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field


class Signal(BaseModel):
    """
    Represents a trading signal generated by a strategy.
    """

    symbol: str = Field(..., description="Trading symbol")
    side: str = Field(..., description="Signal side: 'buy', 'sell', or 'neutral'")
    strength: float = Field(
        default=1.0, description="Signal strength (0.0 to 1.0)"
    )
    strategy: str = Field(..., description="Strategy name that generated signal")
    timestamp: datetime = Field(default_factory=datetime.now, description="Signal timestamp")
    price: Optional[float] = Field(default=None, description="Price at signal time")
    confidence: float = Field(
        default=0.5, description="Confidence level (0.0 to 1.0)"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Additional signal metadata"
    )

    class Config:
        """Pydantic config."""

        json_schema_extra = {
            "example": {
                "symbol": "AAPL",
                "side": "buy",
                "strength": 0.8,
                "strategy": "orb",
                "timestamp": "2024-01-15T10:00:00",
                "price": 150.0,
                "confidence": 0.75,
                "metadata": {"rsi": 35, "macd_histogram": 0.5},
            }
        }
