"""
Signal data model for trading signals from strategies.
"""

from datetime import datetime
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field, field_validator


class Signal(BaseModel):
    """
    Represents a trading signal generated by a strategy.
    Validates signal parameters including strength and confidence ranges.
    """

    symbol: str = Field(..., description="Trading symbol")
    side: str = Field(..., description="Signal side: 'buy', 'sell', or 'neutral'")
    strength: float = Field(
        default=1.0, description="Signal strength (-1.0 to 1.0)"
    )
    strategy: str = Field(..., description="Strategy name that generated signal")
    timestamp: datetime = Field(default_factory=datetime.now, description="Signal timestamp")
    price: Optional[float] = Field(default=None, description="Price at signal time")
    confidence: float = Field(
        default=0.5, description="Confidence level (0.0 to 1.0)"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Additional signal metadata"
    )

    @field_validator("side")
    @classmethod
    def validate_side(cls, v):
        """Validate that side is one of the allowed values."""
        if v not in ("buy", "sell", "neutral"):
            raise ValueError("Side must be 'buy', 'sell', or 'neutral'")
        return v

    @field_validator("strength")
    @classmethod
    def validate_strength(cls, v):
        """Validate that strength is in range -1.0 to 1.0."""
        if v < -1.0 or v > 1.0:
            raise ValueError("Strength must be between -1.0 and 1.0")
        return v

    @field_validator("confidence")
    @classmethod
    def validate_confidence(cls, v):
        """Validate that confidence is in range 0.0 to 1.0."""
        if v < 0.0 or v > 1.0:
            raise ValueError("Confidence must be between 0.0 and 1.0")
        return v

    @field_validator("price")
    @classmethod
    def validate_price(cls, v):
        """Validate that price is positive when provided."""
        if v is not None and v <= 0:
            raise ValueError("Price must be positive")
        return v

    class Config:
        """Pydantic config."""

        json_schema_extra = {
            "example": {
                "symbol": "AAPL",
                "side": "buy",
                "strength": 0.8,
                "strategy": "orb",
                "timestamp": "2024-01-15T10:00:00",
                "price": 150.0,
                "confidence": 0.75,
                "metadata": {"rsi": 35, "macd_histogram": 0.5},
            }
        }
